# Generated by Django 5.2.15 on 2026-07-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=64)),
                ('tunnel_subnet', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('cidr', models.CharField(help_text='e.g. 192.168.20.0/24', max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cas_names', models.JSONField(blank=True, default=list)),
                ('gateways', models.ManyToManyField(blank=True, related_name='groups', to='core.gateway')),
                ('members', models.ManyToManyField(blank=True, related_name='wdg_groups', to=settings.AUTH_USER_MODEL)),
                ('networks', models.ManyToManyField(blank=True, related_name='groups', to='core.network')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('address', models.GenericIPAddressField()),
                ('preshared_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.gateway')),
            ],
            options={
                'ordering': ['user__username', 'gateway__name'],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'address'), name='unique_address_per_gateway')],
            },
        ),
    ]
