# Generated by Django 5.2.15 on 2026-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='sync_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
