# Generated by Django 5.2.15 on 2026-07-03 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gateway_sync_token_alter_gateway_public_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='gateways', to='core.network'),
        ),
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'gateway'), name='unique_device_per_user_gateway'),
        ),
    ]
