# Generated by Django 5.2.15 on 2026-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_multitunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='listen_port',
            field=models.PositiveIntegerField(default=51820),
        ),
    ]
